[package]
name = "ferro"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
termbg = "0.4.1"
termion = "1.5.6"
unicode-segmentation = "1.9.0"
rayon = "1.6.0"
