name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
      - ci/docs

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Generate docs
        run: cargo doc --all --no-deps

      # This step is required since github-pages needs an index.html at the root-level
      - name: Add barebones `index.html`
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=build_wheel\">" > target/doc/index.html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
